### ISSUE TITLE
Notice Detail 불러올 때 Issue_id, standard JOIN

### ISSUE THREAD

**Issue by eunsolkang** [osamhack2022/CLOUD_APP_WEB_IOT_KeepYourEndeavor_Moment#101]
Notice 불러올 때 사용자 결과를 등록해야하는데 해당 기준이랑 이슈정보도 조인해서 반환부탁드립니다...

**Comment by lopahn2** [comment]
사용자의 결과는 /block/push [post] 라우터에서 점수만 넘겨주시면 자동으로 등급을 계산해서 블록단으로 올려줍니다.
같이 함께 고려해봐야 할 점이 
등급은 올라가나 *점수 자체는 어떻게 처리할 것인가 (78점 일경우 이를 보여줄 것인가)* 에 대해 이야기해봐야할 것같습니다.

**Comment by lopahn2** [comment]
issue_id : 추가완료
standard: 추가완료
