### ISSUE TITLE
단일 Standard 불러오기 라우터

### ISSUE THREAD

**Issue by eunsolkang** [osamhack2022/CLOUD_APP_WEB_IOT_KeepYourEndeavor_Moment#102]
/standard/ [GET] 개설자 가능 에서 전체 조회말고 
 
issue_id 기준으로 기준을 따로 불러와야합니다. 

**이거 약간 불편한거 같은데 그냥 issue랑 통합하는것도 고려해보심이 좋을거같습니다.**

**Comment by lopahn2** [comment]
issue 생성시 standard 같이 생성 가능하게 추가하겠습니다. 
- 이미 존재하는 기준일 때는 standard 라우터를 이용
- 아닐경우 기준 생성 완료 라는 내용 리턴
