### ISSUE TITLE
Application User 반환

### ISSUE THREAD

**Issue by eunsolkang** [osamhack2022/CLOUD_APP_WEB_IOT_KeepYourEndeavor_Moment#84]
```json
"message": "현재 신청내역에 있는 모든 인원 현황입니다",
    "members": [
        {
            "rep_id": "supervisor",
            "members": [
                "21-44444444",
                "21-55555555",
                "21-66666666",
                "21-12345678"
            ],
            "message": "대표신청글  테스트 입니다."
        }
    ]
```

해당 부분에서 `Members` 필드가 군번만 반환하는게 아니라 `User Table` 과 조인해서 유저의 정보를 반환해야합니다

**Comment by lopahn2** [comment]
@eunsolkang  https://www.notion.so/oasm2022/2022-10-08-3ed0d2ca23ad4213862f1bed00e6bb46 참고하셔서 필요한 컬럼 알려주세요. 
의도를 보아 affiliation 과의 연동인것 같은데 정확한 table 이름과 필요한 column 명 한 번만 명시 부탁드립니다! '0'//♥

**Comment by eunsolkang** [comment]
@lopahn2 맞습니다 members 에 affiliation 테이블이 join 되어서 나오면 됩니다
