### ISSUE TITLE
fix: CORS 에 *.jerrykang.com 추가

### ISSUE THREAD

**Issue by eunsolkang** [osamhack2022/CLOUD_APP_WEB_IOT_KeepYourEndeavor_Moment#86]
와일드 카드가 불가능하다면 화이트 리스트로
game.jerrykang.com, admin.jerrykang.com 2개 부탁립니다.

**Comment by lopahn2** [comment]
추가 완료했습니다

**Comment by eunsolkang** [comment]
아직 CORS가 날아옵니다 http://game.jerrykang.com 맞는지 확인 부탁드립니다...! @lopahn2
